/** @type {import('next-sitemap').IConfig} */
module.exports = {
	siteUrl: process.env.NEXT_PUBLIC_APP_URL || 'https://verificadordtev2.cuscadev.com',
	generateRobotsTxt: true,
	exclude: [
		'/admin',
		'/admin/*',
		'/api/*',
		'/bancos',
		'/bancos/*',
		'/configuraciones',
		'/consultarjson',
		'/dashboard',
		'/escaneo-qr',
		'/escaneos-mobile',
		'/extraer',
		'/extraer/*',
		'/landing',
		'/login',
		'/mfa-login',
		'/mfa-setup',
		'/profile',
		'/protected',
		'/prrocesardte',
		'/register',
		'/reportes',
		'/reset-password',
		'/totp-verify',
		'/tributario',
		'/usuarios',
		'/verificadorDTE',
		'/verificadorDTE/*',
	],
	robotsTxtOptions: {
		policies: [
			{
				userAgent: '*',
				allow: '/',
				disallow: [
					'/admin',
					'/api',
					'/bancos',
					'/configuraciones',
					'/consultarjson',
					'/dashboard',
					'/escaneo-qr',
					'/escaneos-mobile',
					'/extraer',
					'/landing',
					'/login',
					'/mfa-login',
					'/mfa-setup',
					'/profile',
					'/protected',
					'/prrocesardte',
					'/register',
					'/reportes',
					'/reset-password',
					'/totp-verify',
					'/tributario',
					'/usuarios',
					'/verificadorDTE',
				],
			},
		],
	},
	transform: async (config, path) => ({
		loc: path,
		changefreq: path === '/' ? 'weekly' : 'monthly',
		priority: path === '/' ? 1 : 0.7,
		lastmod: new Date().toISOString(),
	}),
};
